<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lexxys.Tokenizer</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Collections.Immutable" Version="10.0.*" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>

</Project>
