// <auto-generated v="0.90"/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Lexxys;

//#pragma warning disable
#nullable enable

[CliParameters(NamingStyle = ParameterNaming.KebabCase, AllowSlash = true)]
public partial class GeneratedParityModel
{
	[CliOption(Name = "item-count", Alias = ["c"], Required = true)]
	public int Count { get; init; }

	[CliOption(Positional = true, Required = true, ValueName = "INPUT")]
	public string? Input { get; init; }

	[CliOption]
	public int[]? Values { get; init; }

	[CliOption]
	public List<string>? Names { get; init; }

	[CliCommand(Name = "run", Alias = ["r"])]
	public GeneratedRunCommand? Run { get; init; }
}

[CliParameters]
public partial class GeneratedRunCommand
{
	[CliOption]
	public bool Force { get; init; }

	[CliOption("m")]
	public int Mode { get; init; }
}

public class ReflectionParityModel
{
	[CliOption(Name = "item-count", Alias = ["c"], Required = true)]
	public int Count { get; init; }

	[CliOption(Positional = true, Required = true, ValueName = "INPUT")]
	public string? Input { get; init; }

	[CliOption]
	public int[]? Values { get; init; }

	[CliOption]
	public List<string>? Names { get; init; }

	[CliCommand(Name = "run", Alias = ["r"])]
	public ReflectionRunCommand? Run { get; init; }
}

public class ReflectionRunCommand
{
	[CliOption]
	public bool Force { get; init; }

	[CliOption("m")]
	public int Mode { get; init; }
}



public partial class GeneratedParityModel: ICliParameters<GeneratedParityModel>
{
	//public static ParsedArgs<GeneratedParityModel> Parse(IReadOnlyCollection<string> args, ArgumentsConfig config) => Parse(args, new ArgumentsBuilder(config));

	//public static ParsedArgs<GeneratedParityModel> Parse(IReadOnlyCollection<string> args, ArgumentsBuilder? builder = null)
	//{
	//	Args arguments = Args.Parse(args, CreateBuilder(builder));
	//	var error = new List<string>();
	//	var obj = Parse(arguments, error);
	//	return new ParsedArgs<GeneratedParityModel>(arguments, obj, error);
	//}

	public static GeneratedParityModel Parse(IArguments cmd, ICollection<string>? error = null)
	{
		if (cmd is null) throw new ArgumentNullException(nameof(cmd));

		cmd.TryGetValue<int>("item-count", out var p1, errors: error);
		cmd.TryGetValue<string?>(Arguments.FormatArgumentName("Input", cmd.Definition.Config.NamingStyle), out var p2, errors: error);
		cmd.TryGetCollection<int>(Arguments.FormatArgumentName("Values", cmd.Definition.Config.NamingStyle), out var p3, errors: error);
		cmd.TryGetCollection<string>(Arguments.FormatArgumentName("Names", cmd.Definition.Config.NamingStyle), out var p4, errors: error);
		return new GeneratedParityModel
		{
			Count = p1,
			Input = p2,
			Values = p3,
			Names = p4.ToList(),
			Run = cmd.Command?.Name == "run" ? GeneratedRunCommand.Parse(cmd.Command, error): null,
		};
	}

	//public static ArgumentsBuilder CreateBuilder(ArgumentsConfig config) => CreateBuilder(new ArgumentsBuilder(config));

	public static ArgumentsBuilder CreateBuilder(ArgumentsBuilder? builder = null)
	{
//		builder ??= new ArgumentsBuilder(new ArgumentsConfig {  }); <<<<<<<<<< check the property setting
		builder ??= new ArgumentsBuilder();
		return builder
			.Parameter("item-count", __aliases[0], required: true)
			.Positional(Arguments.FormatArgumentName("Input", builder.Config.NamingStyle), valueName: "INPUT", required: true)
			.Parameter(Arguments.FormatArgumentName("Values", builder.Config.NamingStyle), collection: true)
			.Parameter(Arguments.FormatArgumentName("Names", builder.Config.NamingStyle), collection: true)
			.Command<GeneratedRunCommand>("run", __aliases[1]);
	}
	private static readonly string[][] __aliases = [["c"], ["r"]];
}

public partial class GeneratedRunCommand: ICliParameters<GeneratedRunCommand>
{
	//public static ParsedArgs<GeneratedRunCommand> Parse(IReadOnlyCollection<string> args, ArgumentsConfig config) => Parse(args, new ArgumentsBuilder(config));

	// public static ParsedArgs<GeneratedRunCommand> Parse(IReadOnlyCollection<string> args, ArgumentsBuilder? builder = null)
	// {
	// 	Args arguments = Args.Parse(args, CreateBuilder(builder));
	// 	var error = new List<string>();
	// 	var obj = Parse(arguments, error);
	// 	return new ParsedArgs<GeneratedRunCommand>(arguments, obj, error);
	// }

	public static GeneratedRunCommand Parse(IArguments cmd, ICollection<string>? error = null)
	{
		if (cmd is null) throw new ArgumentNullException(nameof(cmd));

		cmd.TryGetValue<bool>(Arguments.FormatArgumentName("Force", cmd.Definition.Config.NamingStyle), out var p1, errors: error);
		cmd.TryGetValue<int>(Arguments.FormatArgumentName("Mode", cmd.Definition.Config.NamingStyle), out var p2, errors: error);
		return new GeneratedRunCommand
		{
			Force = p1,
			Mode = p2,
		};
	}

	//public static ArgumentsBuilder CreateBuilder(ArgumentsConfig config) => CreateBuilder(new ArgumentsBuilder(config));

	public static ArgumentsBuilder CreateBuilder(ArgumentsBuilder? builder = null)
	{
		builder ??= new ArgumentsBuilder(new ArgumentsConfig {  });
		return builder
			.Switch(Arguments.FormatArgumentName("Force", builder.Config.NamingStyle))
			.Parameter(Arguments.FormatArgumentName("Mode", builder.Config.NamingStyle), __aliases[0]);
	}
	private static readonly string[][] __aliases = [["m"]];
}
