<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lexxys</RootNamespace>
    <LangVersion>preview</LangVersion>
    <UnDefineConstants>ERRORRESULT_MUTABLE_DATA</UnDefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>
</Project>
