using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;


namespace Lexxys.Argument.Generator;

[Generator]
public class ArgumentCodeGen: IIncrementalGenerator
{
	private const string CliOptionInterface = "ICliParameters";
	private const string CliParameters = "CliParameters";
	private const string CliCommand = "CliCommand";
	private const string CliOption = "CliOption";
	public const string ArgumentsType = "Arguments";
	public const string ParsedArgumentsType = ArgumentsType;
	public const string ArgumentsInterfaceType = "IArguments";

	public const string IndentString = "\t";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var syntaxProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				(syntaxNode, _) => syntaxNode is AttributeSyntax attribute && attribute.Name.ToString() is CliParameters or CliParameters + "Attribute",
				(syntaxContext, _) => (AttributeSyntax)syntaxContext.Node)
			.Collect();

		context.RegisterSourceOutput(syntaxProvider, Execute);
	}

	public void Execute(SourceProductionContext context, ImmutableArray<AttributeSyntax> attributes)
	{
		if (attributes.IsDefaultOrEmpty) return;

		List<ArgumentClassModel> models = [.. attributes
			.Select(HandleCliArguments)
			.Where(o => o != null)
			.Select(o => o!)];
		models.Sort(ModelsComparer.Instance);

		var text = new StringBuilder();
		text.Append("""
		// <auto-generated v="0.90"/>
		using System;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using Lexxys;

		//#pragma warning disable
		#nullable enable

		""");

		models.Sort((x, y) => String.CompareOrdinal(x.FullName, y.FullName));

		string lastName = String.Empty;
		string lastNamespace = String.Empty;
		int indent = 0;
		foreach (var model in models)
		{
			var fullName = model.FullName;
			int i = fullName.IndexOf('+');
			var thisNamespace = fullName.Substring(0, i);
			var thisName = fullName.Substring(i + 1);

			if (lastNamespace != thisNamespace)
			{
				lastNamespace = thisNamespace;
				while (indent > 0)
				{
					--indent;
					text.Indent(indent).Append("}").AppendLine();
				}
				text.AppendLine();
				if (lastNamespace.Length > 0)
				{
					text.Append("namespace ").Append(lastNamespace).AppendLine()
						.AppendLine("{");
					indent = 1;
				}
				else
				{
					indent = 0;
				}
			}
			else
			{
				while (lastName.Length > 0 && !thisName.StartsWith(lastName + "+"))
				{
					--indent;
					i = lastName.LastIndexOf('+');
					text.Indent(indent).Append("}").AppendLine();
					if (i < 0)
					{
						lastName = String.Empty;
						break;
					}
					lastName = lastName.Substring(0, i);
				}
				text.AppendLine();
			}

			var name = lastName.Length == 0 ? thisName: thisName.Substring(lastName.Length + 1);
			lastName = thisName;
			i = name.IndexOf('+');
			while (i > 0)
			{
				text.Indent(indent).Append(model.Accessibility).Append("partial class ").Append(name, 0, i).AppendLine();
				name = name.Substring(i + 1);
				i = name.IndexOf('+');
				++indent;
			}

			GenerateClass(indent, text, model);
			++indent;
		}

		while (indent > 0)
		{
			--indent;
			text.Indent(indent).Append("}").AppendLine();
		}
		var source = text.ToString();
		context.AddSource("CliGeneratorExtensions_Generated.g.cs", source);
	}

	private static void GenerateClass(int indent, StringBuilder text, ArgumentClassModel model)
	{
		text.Indent(indent).Append(model.Accessibility).AppendLine($"partial class {model.Name}: {CliOptionInterface}<{model.Name}>");
		text.Indent(indent).AppendLine("{");
		++indent;
		text.Indent(indent).AppendLine($"public static {ParsedArgumentsType}<{model.Name}> Parse(IReadOnlyCollection<string> args)");
		text.Indent(indent).AppendLine("{");
		++indent;
		text.Indent(indent).AppendLine($"{ArgumentsType} arguments = {ArgumentsType}.Parse(args, CreateBuilder());");
		text.Indent(indent).AppendLine("var error = new List<string>();");
		text.Indent(indent).AppendLine("var obj = Parse(arguments, error);");
		text.Indent(indent).AppendLine($"return new {ParsedArgumentsType}<{model.Name}>(arguments, obj, error);");
		--indent;
		text.Indent(indent).AppendLine("}");
		text.AppendLine();
		text.Indent(indent).AppendLine($"public static {model.Name} Parse({ArgumentsInterfaceType} cmd, ICollection<string>? error = null)");
		text.Indent(indent).AppendLine("{");
		++indent;

		text.Indent(indent).AppendLine("if (cmd is null) throw new ArgumentNullException(nameof(cmd));").AppendLine();
		CliArgumentsModel? cliArguments = model.Attribute;
		int k = 0;
		foreach (var item in model.Properties)
		{
			if (item.IsCommand) continue;
			var collectionType = GetCollectionElementType(item.Type);
			if (collectionType is null)
			{
				text.Indent(indent).Append("cmd.TryGetValue<").Append(item.Type)
					.Append(">(")
					.AppendArgumentName(item, cliArguments)
					.Append(", out var p").Append(++k).AppendLine(", errors: error);");
				//text.Indent(indent).Append("cmd.Parameters.TryGetValue<").Append(item.Type)
				//	.Append(">(");
				//AppendArgumentName(text, item, "cmd.Definition.NamingStyle")
				//	.Append(", out var p").Append(++k).AppendLine(", error);");
			}
			else
			{
				text.Indent(indent).Append("cmd.TryGetCollection<").Append(collectionType)
					.Append(">(")
					.AppendArgumentName(item, cliArguments)
					.Append(", out var p").Append(++k).AppendLine(", errors: error);");
				//text.Indent(indent).Append("cmd.Parameters.TryGetCollection<").Append(collectionType)
				//	.Append(">(");
				//AppendArgumentName(text, item, "cmd.Definition.NamingStyle")
				//	.Append(", out var p").Append(++k).AppendLine(", error);");
			}
		}
		text.Indent(indent).Append("return new ").AppendLine(model.Name)
			.Indent(indent).AppendLine("{");

		++indent;
		k = 0;
		foreach (var item in model.Properties)
		{
			if (item.IsCommand) continue;
			text.Indent(indent).Append(item.MemberName).Append(" = ");
			AppendCollectionAssignment(text, item.Type, "p" + ++k).AppendLine(",");
		}
		foreach (var item in model.Properties)
		{
			if (!item.IsCommand) continue;
			text.Indent(indent).Append(item.MemberName)
				.Append(" = cmd.Command?.Name == ")
				.AppendArgumentName(item, cliArguments)
				.Append(" ? ").Append(item.Type?.TrimEnd('?')).AppendLine(".Parse(cmd.Command, error): null,");
		}
		--indent;
		text.Indent(indent).AppendLine("};");
		--indent;
		text.Indent(indent).AppendLine("}");

		List<string[]> aliases = [.. model.Properties
			.Select(o => o.ParamAttribute?.Alias ?? o.CommandAttribute?.Alias ?? [])
			.Where(o => o.Length > 0)];
		if (aliases.Count > 0)
		{
			for (var i = 0; i < aliases.Count; ++i)
			{
				Array.Sort(aliases[i]);
			}
			aliases = [.. aliases.Distinct(AliasEqualityComparer.Instance)];
		}

		//text.AppendLine();
		//text.Indent(indent).AppendLine("public static ArgumentsBuilder CreateBuilder(ArgumentsConfig config) => CreateBuilder(new ArgumentsBuilder(config));");

		text.AppendLine();
		text.Indent(indent).AppendLine("public static ArgumentsBuilder CreateBuilder(ArgumentsBuilder? builder = null)");
		text.Indent(indent).AppendLine("{");
		++indent;
		text.Indent(indent).Append("builder ??= new ArgumentsBuilder(");
		AppendSettings(text, model.Attribute).AppendLine(");");
		text.Indent(indent).Append("return builder");
		foreach (var item in model.Properties)
		{
			if (item.IsCommand) continue;
			var attrib = item.ParamAttribute;

			bool positional = IsTrueLiteral(attrib?.Positional);
			bool required = IsTrueLiteral(attrib?.Required);
			bool collection = GetCollectionElementType(item.Type) is not null;
			bool toggle = IsSwitchType(item.Type);

			text.AppendLine().Append('\t', indent + 1);
			if (positional)
			{
				text.Append(".Positional(")
					.AppendArgumentName(item, cliArguments);
				if (attrib?.Description is { Length: > 0 })
					text.Append(", description: ").Append(attrib.Description);
				if (attrib?.ValueName is { Length: > 0 })
					text.Append(", valueName: ").Append(attrib.ValueName);
				if (collection)
					text.Append(", collection: true");
				if (required)
					text.Append(", required: true");
				text.Append(')');
			}
			else if (toggle)
			{
				text.Append(".Switch(")
					.AppendArgumentName(item, cliArguments);
				if (attrib?.Alias is { Length: > 0 })
					text.Append(", __aliases[").Append(aliases.FindIndex(o => AliasEqualityComparer.Instance.Equals(o, attrib.Alias))).Append(']');
				if (attrib?.Description is { Length: > 0 })
					text.Append(", description: ").Append(attrib.Description);
				text.Append(')');
			}
			else
			{
				text.Append(".Parameter(")
					.AppendArgumentName(item, cliArguments);
				if (attrib?.Alias is { Length: > 0 })
					text.Append(", __aliases[").Append(aliases.FindIndex(o => AliasEqualityComparer.Instance.Equals(o, attrib.Alias))).Append(']');
				if (attrib?.ValueName is { Length: > 0 })
					text.Append(", valueName: ").Append(attrib.ValueName);
				if (attrib?.Description is { Length: > 0 })
					text.Append(", description: ").Append(attrib.Description);
				if (collection)
					text.Append(", collection: true");
				if (required)
					text.Append(", required: true");
				text.Append(')');
			}
		}

		foreach (var item in model.Properties)
		{
			if (!item.IsCommand) continue;
			var attrib = item.CommandAttribute;
			text.AppendLine()
				.Append('\t', indent + 1)
				.Append(".Command<").Append(item.Type?.TrimEnd('?')).Append(">(")
				.AppendArgumentName(item, cliArguments);
			if (attrib?.Alias is { Length: > 0 })
				text.Append(", __aliases[").Append(aliases.FindIndex(o => AliasEqualityComparer.Instance.Equals(o, attrib.Alias))).Append(']');
			if (attrib?.Description is { Length: > 0 })
				text.Append(", description: ").Append(attrib.Description);
			text.Append(')');
		}
		text.AppendLine(";");
		--indent;
		text.Indent(indent).AppendLine("}");

		if (aliases.Count > 0)
		{
			text.Indent(indent).Append("private static readonly string[][] __aliases = [[");
			for (int i = 0; i < aliases.Count; ++i)
			{
				if (i > 0)
					text.Append("], [");
				text.Append(String.Join(", ", aliases[i]));
			}
			text.AppendLine("]];");
		}

		static bool IsTrueLiteral(string? value)
			=> value is not null && String.Equals(value.Trim(), "true", StringComparison.OrdinalIgnoreCase);

		static bool IsSwitchType(string? typeName)
		{
			if (String.IsNullOrWhiteSpace(typeName))
				return false;
			var type = typeName!.Trim().TrimEnd('?');
			return type is "bool" or "Boolean" or "System.Boolean";
		}

		static string? GetCollectionElementType(string? typeName)
		{
			if (String.IsNullOrWhiteSpace(typeName))
				return null;

			var type = typeName!.Trim().TrimEnd('?');
			if (String.Equals(type, "string", StringComparison.OrdinalIgnoreCase) || String.Equals(type, "System.String", StringComparison.Ordinal))
				return null;

			if (type.EndsWith("[]", StringComparison.Ordinal))
				return type.Substring(0, type.Length - 2);

			var i = type.IndexOf('<');
			if (i < 0 || !type.EndsWith(">", StringComparison.Ordinal))
				return null;

			var genericName = type.Substring(0, i);
			var elementType = type.Substring(i + 1, type.Length - i - 2);

			return genericName is "IEnumerable" or "System.Collections.Generic.IEnumerable"
				or "IReadOnlyCollection" or "System.Collections.Generic.IReadOnlyCollection"
				or "IReadOnlyList" or "System.Collections.Generic.IReadOnlyList"
				or "ICollection" or "System.Collections.Generic.ICollection"
				or "IList" or "System.Collections.Generic.IList"
				or "List" or "System.Collections.Generic.List"
				or "HashSet" or "System.Collections.Generic.HashSet"
				? elementType
				: null;
		}

		static StringBuilder AppendCollectionAssignment(StringBuilder text, string? typeName, string variableName)
		{
			var elementType = GetCollectionElementType(typeName);
			if (elementType is null)
				return text.Append(variableName);

			var type = typeName!.Trim().TrimEnd('?');
			if (type.EndsWith("[]", StringComparison.Ordinal)
				|| type.StartsWith("IEnumerable<", StringComparison.Ordinal)
				|| type.StartsWith("System.Collections.Generic.IEnumerable<", StringComparison.Ordinal)
				|| type.StartsWith("IReadOnlyCollection<", StringComparison.Ordinal)
				|| type.StartsWith("System.Collections.Generic.IReadOnlyCollection<", StringComparison.Ordinal)
				|| type.StartsWith("IReadOnlyList<", StringComparison.Ordinal)
				|| type.StartsWith("System.Collections.Generic.IReadOnlyList<", StringComparison.Ordinal)
				|| type.StartsWith("ICollection<", StringComparison.Ordinal)
				|| type.StartsWith("System.Collections.Generic.ICollection<", StringComparison.Ordinal)
				|| type.StartsWith("IList<", StringComparison.Ordinal)
				|| type.StartsWith("System.Collections.Generic.IList<", StringComparison.Ordinal))
				return text.Append(variableName);

			if (type.StartsWith("HashSet<", StringComparison.Ordinal) || type.StartsWith("System.Collections.Generic.HashSet<", StringComparison.Ordinal))
				return text.Append("new HashSet<").Append(elementType).Append(">(").Append(variableName).Append(')');

			return text.Append(variableName).Append(".ToList()");
		}

		static StringBuilder AppendSettings(StringBuilder text, CliArgumentsModel? model)
		{
			if (model is null)
				return text.Append("ArgumentsConfig.Default");

			var values = new (string Name, string? Value)[]
			{
				(nameof(CliArgumentsModel.IgnoreCase), model.IgnoreCase),
				(nameof(CliArgumentsModel.AllowSlash), model.AllowSlash),
				(nameof(CliArgumentsModel.Strict), model.Strict),
				(nameof(CliArgumentsModel.AllowUnknown), model.AllowUnknown),
				(nameof(CliArgumentsModel.ColonSeparator), model.ColonSeparator),
				(nameof(CliArgumentsModel.EqualSeparator), model.EqualSeparator),
				(nameof(CliArgumentsModel.BlankSeparator), model.BlankSeparator),
				(nameof(CliArgumentsModel.NamingStyle), model.NamingStyle),
				(nameof(CliArgumentsModel.MatchingType), model.MatchingType),
			};
			if (values.All(o => String.IsNullOrEmpty(o.Value)))
				return text.Append("ArgumentsConfig.Default");

			text.Append("new ArgumentsConfig { ");
			bool first = true;
			foreach (var (name, value) in values)
			{
				if (value is not { Length: > 0 })
					continue;
				if (first)
					first = false;
				else
					text.Append(", ");
				text.Append(name).Append(" = ").Append(value);
			}
			return text.Append(" }");
		}

		//static StringBuilder AppendArgumentName(StringBuilder text, ArgumentPropertyModel item, string namingStyle)
		//{
		//	if (item.ExplicitName is not null)
		//		return text.Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(item.ExplicitName, quote: true));

		//	return text.Append($"{ArgumentsType}.FormatArgumentName(")
		//		.Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(item.MemberName ?? String.Empty, quote: true))
		//		.Append(", ").Append(namingStyle).Append(')');
		//}
	}

	class ModelsComparer: IComparer<(ArgumentClassModel Model, List<string>)>, IComparer<ArgumentClassModel>
	{
		public static readonly ModelsComparer Instance = new ModelsComparer();

		public int Compare((ArgumentClassModel Model, List<string>) x, (ArgumentClassModel Model, List<string>) y)
			=> String.Compare(x.Model.FullName, y.Model.FullName, StringComparison.Ordinal);

		public int Compare(ArgumentClassModel x, ArgumentClassModel y)
			=> String.Compare(x.FullName, y.FullName, StringComparison.Ordinal);
	}

	private class AliasEqualityComparer: EqualityComparer<string[]?>
	{
		public static readonly EqualityComparer<string[]?> Instance = new AliasEqualityComparer();

		public override bool Equals(string[]? x, string[]? y)
		{
			if (x is not { Length: >0 }) return y is not { Length: >0 };
			if (y is not { Length: > 0 }) return false;
			if (x.Length != y.Length) return false;
			for (var i = 0; i < x.Length; ++i)
			{
				if (x[i] != y[i]) return false;
			}
			return true;
		}

		public override int GetHashCode(string[]? obj)
		{
			return obj is null ? 0: obj.Aggregate(obj.Length, (current, s) => unchecked(current * 31 + s.GetHashCode()));
		}
	}

	private ArgumentClassModel? HandleCliArguments(AttributeSyntax attrib)
	{
		var argAttribute = HandleCliArgumentsAttribute(attrib);
		if (attrib.Parent?.Parent is not ClassDeclarationSyntax classDeclaration)
			return null;
		var className = classDeclaration.Identifier.ValueText;
		var classNameSpace = GetNameSpace(classDeclaration);
		var classRecord = new ArgumentClassModel(className, classNameSpace, GetAccessibility(classDeclaration.Modifiers), argAttribute);

		foreach (var member in classDeclaration.Members)
		{
			CliParamModel? paramAttribute = GetParamAttribute(member);
			CliCommandModel? commandAttribute = GetCommandAttribute(member);

			if (member is PropertyDeclarationSyntax property)
			{
				if (!CheckModifiers(property.Modifiers))
					continue;
				var propertyType = property.Type;
				var propertyName = property.Identifier.ValueText;
				ArgumentPropertyModel arg = new ArgumentPropertyModel(name: propertyName, propertyType.ToString(), paramAttribute, commandAttribute);
				classRecord.Properties.Add(arg);
			}
			else if (member is FieldDeclarationSyntax field)
			{
				if (!CheckModifiers(field.Modifiers))
					continue;
				var propertyType = field.Declaration.Type;
				foreach (var variable in field.Declaration.Variables)
				{
					var propertyName = variable.Identifier.ValueText;
					ArgumentPropertyModel arg = new ArgumentPropertyModel(name: propertyName, propertyType.ToString(), paramAttribute, commandAttribute);
					classRecord.Properties.Add(arg);
				}
			}

			static bool CheckModifiers(SyntaxTokenList modifiers)
			{
				bool valid = false;
				foreach (var item in modifiers)
				{
					if (item.ValueText is "static" or "readonly" or "abstract")
						return false;
					if (item.ValueText is "public" or "protected" or "internal")
						valid = true;
				}
				return valid;
			}
		}

		return classRecord;
	}

	private CliCommandModel? GetCommandAttribute(MemberDeclarationSyntax? member)
	{
		if (member == null) return null;
		AttributeSyntax? attrib = member.AttributeLists.SelectMany(o => o.Attributes).FirstOrDefault(a => a.Name.ToString() is CliCommand or CliCommand + "Attribute");
		if (attrib == null) return null;

		IDictionary<string, string> optional = GetFieldsAssignment(attrib);
		string[] alias = optional.TryGetValue("Alias", out var aliasExpression) ? GetAliasValues(aliasExpression): GetAliasParameter(attrib);

		var pm = new CliCommandModel(
			Name: GetStringValue(optional.GetValueOrDefault("Name")),
			Alias: alias,
			Description: optional.GetValueOrDefault("Description"));
		return pm;
	}

	private string[] GetAliasParameter(AttributeSyntax attrib)
	{
		List<(string? Name, AttributeArgumentSyntax Arg)>? attribPositional = GetPositionalParameters(attrib);
		if (attribPositional == null) return [];

		List<string> result = [];
		foreach (var (_, arg) in attribPositional)
		{
			ExpressionSyntax exp = arg.Expression;
			if (exp is CollectionExpressionSyntax collection)
				result.AddRange(collection.Elements.Select(o => o.ToString()));
			else if (exp is ImplicitArrayCreationExpressionSyntax { Initializer: not null } implicitArray)
				result.AddRange(implicitArray.Initializer.Expressions.Select(o => o.ToString()));
			else if (exp is ArrayCreationExpressionSyntax { Initializer: not null } array)
				result.AddRange(array.Initializer.Expressions.Select(o => o.ToString()));
			else
				result.Add(exp.ToString());
		}
		return [.. result];
	}

	private List<(string? Name, AttributeArgumentSyntax Arg)>? GetPositionalParameters(AttributeSyntax attrib)
	{
		if (attrib.ArgumentList == null) return null;
		SeparatedSyntaxList<AttributeArgumentSyntax> args = attrib.ArgumentList.Arguments;
		if (args.Count == 0) return null;
		List<(string? Name, AttributeArgumentSyntax Arg)> selected = [.. args.Where(o => o.NameEquals == null).Select(o => (o.NameColon?.Name.Identifier.ValueText, o))];
		return selected.Count == 0 ? null: selected;
	}

	private Dictionary<string, string> GetFieldsAssignment(AttributeSyntax attrib)
	{
		List<(string Name, AttributeArgumentSyntax Arg)>? attribOptional = GetOptionalParameters(attrib);
		return attribOptional?.ToDictionary(
			o => o.Name,
			o => o.Arg.Expression.ToString()
			) ?? __localEmpty;
	}
	private static readonly Dictionary<string, string> __localEmpty = [];

	private CliParamModel? GetParamAttribute(MemberDeclarationSyntax? member)
	{
		if (member == null) return null;
		AttributeSyntax? attrib = member.AttributeLists.SelectMany(o => o.Attributes).FirstOrDefault(a => a.Name.ToString() is CliOption or CliOption + "Attribute");
		if (attrib == null) return null;

		IDictionary<string, string> optional = GetFieldsAssignment(attrib);
		string[] alias = optional.TryGetValue("Alias", out var aliasExpression) ? GetAliasValues(aliasExpression): GetAliasParameter(attrib);

		var pm = new CliParamModel(
			Name: GetStringValue(optional.GetValueOrDefault("Name")),
			Alias: alias,
			ValueName: optional.GetValueOrDefault("ValueName"),
			Description: optional.GetValueOrDefault("Description"),
			Positional: optional.GetValueOrDefault("Positional"),
			Required: optional.GetValueOrDefault("Required"));
		return pm;
	}

	private List<(string Name, AttributeArgumentSyntax Arg)>? GetOptionalParameters(AttributeSyntax attrib)
	{
		if (attrib.ArgumentList == null) return null;
		SeparatedSyntaxList<AttributeArgumentSyntax> args = attrib.ArgumentList.Arguments;
		if (args.Count == 0) return null;
		List<(string Name, AttributeArgumentSyntax Arg)> selected = [.. args.Where(o => o.NameEquals != null).Select(o => (o.NameEquals!.Name.Identifier.ValueText, o))];
		return selected.Count == 0 ? null: selected;
	}

	private string GetNameSpace(ClassDeclarationSyntax classDeclaration)
	{
		var parent = classDeclaration.Parent;
		return parent switch
		{
			NamespaceDeclarationSyntax ns => ns.Name.ToString(),
			FileScopedNamespaceDeclarationSyntax fns => fns.Name.ToString(),
			ClassDeclarationSyntax cls => GetNameSpace(cls) + "+" + cls.Identifier.ValueText,
			_ => String.Empty
		};
	}

	private static string GetAccessibility(SyntaxTokenList modifiers)
	{
		foreach (var item in modifiers)
		{
			if (item.ValueText is "public" or "internal" or "protected" or "private")
				return item.ValueText + " ";
		}
		return String.Empty;
	}

	private CliArgumentsModel HandleCliArgumentsAttribute(AttributeSyntax attrib)
	{
		var optional = GetFieldsAssignment(attrib);
		return new CliArgumentsModel(
			IgnoreCase: optional.GetValueOrDefault("IgnoreCase"),
			AllowSlash: optional.GetValueOrDefault("AllowSlash"),
			Strict: optional.GetValueOrDefault("Strict"),
			AllowUnknown: optional.GetValueOrDefault("AllowUnknown"),
			ColonSeparator: optional.GetValueOrDefault("ColonSeparator"),
			EqualSeparator: optional.GetValueOrDefault("EqualSeparator"),
			BlankSeparator: optional.GetValueOrDefault("BlankSeparator"),
			NamingStyle: optional.GetValueOrDefault("NamingStyle"),
			MatchingType: optional.GetValueOrDefault("MatchingType"));
	}

	private static string? GetStringValue(string? expression)
	{
		if (expression is not { Length: > 1 })
			return expression;
		expression = expression.Trim();
		return expression.Length > 1 && expression[0] == '"' && expression[expression.Length - 1] == '"'
			? expression.Substring(1, expression.Length - 2)
			: expression;
	}

	private static string[] GetAliasValues(string expression)
	{
		expression = expression.Trim();
		if (expression.Length == 0)
			return [];
		if (expression[0] == '[' && expression[expression.Length - 1] == ']')
			expression = expression.Substring(1, expression.Length - 2);
		else if (expression.StartsWith("new[]", StringComparison.Ordinal))
		{
			var i = expression.IndexOf('{');
			var j = expression.LastIndexOf('}');
			expression = i < 0 || j <= i ? String.Empty: expression.Substring(i + 1, j - i - 1);
		}

		return [.. expression.Split([','], StringSplitOptions.RemoveEmptyEntries).Select(o => o.Trim())];
	}

	class SyntaxReceiver: ISyntaxReceiver
	{
		public List<AttributeSyntax> Attributes { get; } = [];

		public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
		{
			if (syntaxNode is not AttributeSyntax attribute) return;
			var attributeName = attribute.Name.ToString();
			if (attributeName is CliParameters or CliParameters + "Attribute")
			{
				Attributes.Add(attribute);
			}
		}
	}
}
