// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: SuppressMessage("Build", "CA1805:Member 'Start' is explicitly initialized to its default value (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1805)", Justification = "<Pending>", Scope = "member", Target = "~F:Lexxys.Tokenizer.CharPosition.Start")]
[assembly: SuppressMessage("Build", "CA1508:'__assemblies == null' is always 'true'. Remove or refactor the condition(s) to avoid dead code. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508)", Justification = "<Pending>", Scope = "member", Target = "~M:Lexxys.Factory.CollectAssemblies")]
[assembly: SuppressMessage("Build", "CA1508:'__assemblies == null' is always 'true'. Remove or refactor the condition(s) to avoid dead code. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508)", Justification = "<Pending>", Scope = "member", Target = "~M:Lexxys.Factory.CollectOrImportAssemblies")]
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string? Strings.ToNamingRule(string? value, NamingCaseRule rule)', validate parameter 'value' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1062)", Justification = "<Pending>", Scope = "member", Target = "~M:Lexxys.Strings.ToNamingRule(System.String,Lexxys.NamingCaseRule)~System.String")]
[assembly: SuppressMessage("Build", "CA1819:Properties should not return arrays (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1819)", Justification = "<Pending>", Scope = "member", Target = "~P:Lexxys.JsonScalar.BytesValue")]
[assembly: SuppressMessage("Build", "CA1819:Properties should not return arrays (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1819)", Justification = "<Pending>", Scope = "member", Target = "~P:Lexxys.ParameterDefinition.Abbrev")]
[assembly: SuppressMessage("Build", "CA1711:Rename type name CharStream so that it does not end in 'Stream' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1711)", Justification = "<Pending>", Scope = "type", Target = "~T:Lexxys.Tokenizer.CharStream")]
[assembly: SuppressMessage("Build", "CA1815:LexicalToken should override Equals (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1815)", Justification = "<Pending>", Scope = "type", Target = "~T:Lexxys.Tokenizer.LexicalToken")]
[assembly: SuppressMessage("Build", "CA1034:Do not nest type Node. Alternatively, change its accessibility so that it is not externally visible. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1034)", Justification = "<Pending>", Scope = "type", Target = "~T:Lexxys.Xml.TextToXmlConverter.Node")]
