<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <RootNamespace>Lexxys.Data</RootNamespace>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexxys\Lexxys.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.*" Condition="'$(TargetFramework)'!='netstandard2.0'" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.*" Condition="'$(TargetFramework)'=='netstandard2.0'" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lexxys.Logging" />
    <InternalsVisibleTo Include="Lexxys.Legacy" />
    <InternalsVisibleTo Include="Lexxys.Tests" />
    <InternalsVisibleTo Include="Lexxys.Xml" />
    <InternalsVisibleTo Include="Lexxys.Test.Console" />
    <InternalsVisibleTo Include="Lexxys.Validation" />
    <InternalsVisibleTo Include="TestPizza" />
  </ItemGroup>

</Project>
