<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <AssemblyMetadata Include="ConfigFile" Value="test.config.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.*" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lexxys.DataContext\Lexxys.DataContext.csproj" />
    <ProjectReference Include="..\..\src\Lexxys.Testing\Lexxys.Testing.csproj" />
    <ProjectReference Include="..\..\src\Lexxys.Validation\Lexxys.Validation.csproj" />
    <ProjectReference Include="..\..\src\Lexxys\Lexxys.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Crypting\**" />
    <Compile Remove="Results\**" />
    <EmbeddedResource Remove="Results\**" />
    <None Remove="Results\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="LocalFileStorageServiceTests.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="application.config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test.config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test.db.config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
