// Lexxys Infrastructural library.
// file: IRand.cs
//
// Copyright (c) 2001-2014, Kraft Pro Utilities.
// You may use this code under the terms of the MIT license
//

namespace Lexxys.Testing;

/// <summary>
/// Defines a contract for generating random numbers of various types and for reseeding the random number generator.
/// </summary>
/// <remarks>Implementations of this interface provide methods to generate random integers, long values,
/// double-precision floating-point numbers, and to fill byte arrays with random data. The interface also allows
/// resetting the generator with a specific seed to produce repeatable sequences, if supported. Thread safety and the
/// quality of randomness may vary between implementations.</remarks>
public interface IRand
{
	/// <summary>
	/// Resets the generator to its initial state, optionally using the specified seed value.
	/// </summary>
	/// <remarks>Use this method to reinitialize the generator for repeatable sequences or to start a new sequence.
	/// The behavior when using a seed of 0 may vary depending on the implementation.</remarks>
	/// <param name="seed">The seed value to initialize the generator. If 0, a default or time-based seed may be used.</param>
	void Reset(long seed = 0);

	/// <summary>
	/// Returns a non-negative random integer.
	/// </summary>
	/// <returns>A 32-bit signed integer that is greater than or equal to 0.</returns>
	int NextInt32();

	/// <summary>
	/// Returns a non-negative random long value.
	/// </summary>
	/// <returns>A 64-bit signed integer that is greater than or equal to 0.</returns>
	long NextInt64();

	/// <summary>
	/// Returns a random floating-point number that is greater than or equal to 0.0, and less than 1.0.
	/// </summary>
	/// <returns>A double-precision floating-point number greater than or equal to 0.0, and less than 1.0.</returns>
	double NextDouble();

	/// <summary>
	/// Fills the elements of a specified span of bytes with random values.
	/// </summary>
	/// <remarks>Each call to this method overwrites the entire contents of the provided span. The randomness and
	/// distribution of the generated bytes depend on the implementation.</remarks>
	/// <param name="buffer">The span to fill with random bytes. The contents of the span are replaced with random values.</param>
	void NextBytes(Span<byte> buffer);
}