namespace Lexxys.Testing;

/// <summary>
/// Provides static factory methods for creating and manipulating random value generators and weighted random item
/// selectors.
/// </summary>
/// <remarks>
/// The R class offers a variety of methods to construct instances of <see cref="RandItem{T}"/> for generating random
/// values, including numbers, characters, strings, and custom objects, with support for weighted selection, filtering,
/// and formatting. It also includes utilities for loading and parsing data from files, and for generating random text
/// and patterns. All members are thread-safe for typical usage, as they do not maintain internal mutable
/// state.
/// </remarks>
public static partial class R
{
	private const int DefaultMaxTries = 9999;

	/// <summary>
	/// Creates a random item selector that returns a randomly chosen element from the specified items each time it is
	/// invoked.
	/// </summary>
	/// <remarks>If the array contains duplicate items, each occurrence has an equal chance of being selected. The
	/// selection is performed independently on each invocation.</remarks>
	/// <typeparam name="T">The type of the items to select from.</typeparam>
	/// <param name="items">The array of items to select from. Cannot be null or empty.</param>
	/// <returns>A <see cref="RandItem{T}"/> that, when evaluated, returns a randomly selected item from the provided array.</returns>
	public static RandItem<T> Any<T>(params T[] items) => new RandItem<T>(() => Rand.Item(items));

	/// <summary>
	/// Returns a random item from the specified sequence, or an empty result if the sequence is null or contains no
	/// elements.
	/// </summary>
	/// <remarks>
	/// If the sequence contains exactly one element, that element is always returned. If the sequence
	/// contains more than one element, a random item is selected each time the <see cref="RandItem{T}"/> is evaluated. The method
	/// materializes the input sequence; avoid passing large or infinite sequences.
	/// </remarks>
	/// <typeparam name="T">The type of elements in the input sequence.</typeparam>
	/// <param name="items">The sequence of items to select from. Can be null.</param>
	/// <returns>
	/// A <see cref="RandItem{T}"/> representing a randomly selected item from the sequence. If the sequence is null or empty, returns
	/// <see cref="RandItem{T}.Empty"/>.
	/// </returns>
	public static RandItem<T> Any<T>(IEnumerable<T>? items)
	{
		if (items == null)
			return RandItem<T>.Empty;

		var vv = items.ToList();
		if (vv.Count == 0)
			return RandItem<T>.Empty;
		if (vv.Count > 1)
			return new RandItem<T>(() => Rand.Item(vv));
		var v = vv[0];
		return new RandItem<T>(v);
	}

	/// <summary>
	/// Creates a new <see cref="RandItem{T}"/> instance containing the specified value.
	/// </summary>
	/// <typeparam name="T">The type of the value to be wrapped by the <see cref="RandItem{T}"/>.</typeparam>
	/// <param name="value">The value to be encapsulated in the <see cref="RandItem{T}"/> instance.</param>
	/// <returns>A <see cref="RandItem{T}"/> that contains the specified value.</returns>
	public static RandItem<T> I<T>(T value) => new RandItem<T>(value);

	/// <summary>
	/// Creates a new random item with the specified weight and value.
	/// </summary>
	/// <typeparam name="T">The type of the value to associate with the random item.</typeparam>
	/// <param name="weight">The relative probability weight assigned to the item. Must be non-negative.</param>
	/// <param name="value">The value to associate with the random item.</param>
	/// <returns>A new instance of <see cref="RandItem{T}"/> containing the specified weight and value.</returns>
	public static RandItem<T> I<T>(double weight, T value) => new RandItem<T>(weight, value);

	/// <summary>
	/// Creates a new instance of the <see cref="RandItem{T}"/> class using the specified value generator and a default
	/// weight of 1.0.
	/// </summary>
	/// <typeparam name="T">The type of value generated by the <paramref name="generator"/> function.</typeparam>
	/// <param name="generator">A function that generates values of type <typeparamref name="T"/> when invoked. Cannot be null.</param>
	/// <returns>A new <see cref="RandItem{T}"/> initialized with the specified value generator and a weight of 1.0.</returns>
	public static RandItem<T> I<T>(Func<T> generator) => new RandItem<T>(generator);

	/// <summary>
	/// Creates a new random item with the specified weight and value generator.
	/// </summary>
	/// <typeparam name="T">The type of value produced by the generator.</typeparam>
	/// <param name="weight">The relative probability weight assigned to this item. Must be non-negative.</param>
	/// <param name="generator">A function that generates the value for this item when selected. Cannot be null.</param>
	/// <returns>A new <see cref="RandItem{T}"/> instance configured with the specified weight and generator.</returns>
	public static RandItem<T> I<T>(double weight, Func<T> generator) => new RandItem<T>(weight, generator);

	/// <summary>
	/// Creates a new random item as a composition of the specified items.
	/// </summary>
	/// <remarks>Use this method to compose a random item from multiple existing random items. The selection
	/// behavior depends on the implementation of <see cref="RandItem{T}"/>.</remarks>
	/// <typeparam name="T">The type of the values contained in the random items.</typeparam>
	/// <param name="items">An array of random items to select from. Cannot be null or empty.</param>
	/// <returns>A new <see cref="RandItem{T}"/> instance that represents a random selection from the provided items.</returns>
	public static RandItem<T> I<T>(params RandItem<T>[] items) => new RandItem<T>(items);

	/// <summary>
	/// Creates a new random item selector from a collection of random items.
	/// </summary>
	/// <typeparam name="T">The type of value contained in each random item.</typeparam>
	/// <param name="items">The collection of random items to include in the selector. Cannot be null.</param>
	/// <returns>A new <see cref="RandItem{T}"/> instance initialized with the specified collection of random items.</returns>
	public static RandItem<T> I<T>(IEnumerable<RandItem<T>> items) => new RandItem<T>(items);

	/// <summary>
	/// Creates a composite random item from a set of weighted value pairs.
	/// </summary>
	/// <remarks>The resulting <see cref="RandItem{T}"/> can be used to perform random selections where each value's likelihood is
	/// proportional to its specified weight.</remarks>
	/// <typeparam name="T">The type of the values to associate with each weight.</typeparam>
	/// <param name="pairs">An array of tuples, each containing a weight and a value. The weight determines the relative probability of
	/// selecting the associated value. All weights must be greater than zero.</param>
	/// <returns>A <see cref="RandItem{T}"/> instance representing a weighted random selection among the provided values.</returns>
	public static RandItem<T> I<T>(params (double Weight, T Value)[] pairs) => new RandItem<T>(Array.ConvertAll(pairs, o => new RandItem<T>(o.Weight, o.Value)), false);

	/// <summary>
	/// Creates a new random item with the specified weight and existing random item.
	/// </summary>
	/// <typeparam name="T">The type of the value to associate with the random item.</typeparam>
	/// <param name="weight">The positive relative weight to assign to the item.</param>
	/// <param name="value">The existing <see cref="RandItem{T}"/> to wrap with the specified weight.</param>
	/// <returns>A <see cref="RandItem{T}"/> instance containing the specified value and weight.</returns>
	public static RandItem<T> I<T>(double weight, RandItem<T> value) => value.WithWeight(weight);

	/// <summary>
	/// Creates a random item generator that produces values using the specified generator and only returns values that
	/// satisfy the given filter.
	/// </summary>
	/// <remarks>This method is useful when you need to generate random values that must meet specific criteria. If
	/// a suitable value cannot be found within the specified number of tries, an exception is thrown. The default maximum
	/// number of tries is used if <paramref name="maxTries"/> is not specified or is less than or equal to zero.</remarks>
	/// <typeparam name="T">The type of value to generate.</typeparam>
	/// <param name="generator">A function that generates candidate values of type T. Cannot be null.</param>
	/// <param name="filter">A predicate used to determine whether a generated value is acceptable. Only values for which this function returns
	/// <see langword="true"/> will be returned. Cannot be null.</param>
	/// <param name="maxTries">The maximum number of attempts to generate a value that satisfies the filter. If zero, a default
	/// maximum is used.</param>
	/// <returns>A <see cref="RandItem{T}"/> that generates values from the specified generator, filtered by the provided predicate.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="generator"/> or <paramref name="filter"/> is null.</exception>
	/// <exception cref="InvalidOperationException">Thrown if no value satisfying the filter is generated within the allowed number of attempts.</exception>
	public static RandItem<T> I<T>(Func<T> generator, Func<T, bool> filter, int maxTries = 0)
	{
		if (generator == null)
			throw new ArgumentNullException(nameof(generator));
		if (filter == null)
			throw new ArgumentNullException(nameof(filter));
		if (maxTries <= 0)
			maxTries = DefaultMaxTries;

		return new RandItem<T>(() =>
		{
			for (int i = 0; i < maxTries; ++i)
			{
				var t = generator();
				if (filter(t))
					return t;
			}
			throw new InvalidOperationException($"Cannot find an appropriate item value in {maxTries} tries.");
		});
	}

	/// <summary>
	/// Creates a new random item generator that produces values from the specified <see cref="RandItem{T}"/> and
	/// only returns values that satisfy the given <paramref name="filter"/>.
	/// </summary>
	/// <remarks>If maxTries is set to 0, the method will continue attempting to generate values until the filter
	/// condition is met. If maxTries is greater than 0, the method will stop after the specified number of attempts and
	/// return an unsuccessful result if no value satisfies the filter.</remarks>
	/// <typeparam name="T">The type of value generated and filtered.</typeparam>
	/// <param name="generator">The random value generator to use for producing candidate values. Cannot be null.</param>
	/// <param name="filter">A predicate that determines whether a generated value is accepted. Cannot be null.</param>
	/// <param name="maxTries">The maximum number of attempts to generate a value that satisfies the filter. Specify 0 for unlimited attempts.</param>
	/// <returns>A <see cref="RandItem{T}"/> containing the first value that satisfies the filter, or an unsuccessful result if no such value is
	/// found within the allowed number of tries.</returns>
	/// <exception cref="ArgumentNullException">Thrown if either generator or filter is null.</exception>
	public static RandItem<T> I<T>(RandItem<T> generator, Func<T, bool> filter, int maxTries = 0)
	{
		if (generator == null)
			throw new ArgumentNullException(nameof(generator));
		if (filter == null)
			throw new ArgumentNullException(nameof(filter));
		return I(generator.NextValue, filter, maxTries);
	}
}
