namespace Lexxys.Testing;

/// <summary>
/// Extension methods for collections of the random generators.
/// </summary>
public static class RandItemCollectionExtensions
{
	/// <summary>
	/// Returns an array containing the values generated by all items in the specified collection.
	/// </summary>
	/// <typeparam name="T">The type of the values contained in the collection.</typeparam>
	/// <param name="collection">The collection of <see cref="RandItem{T}"/> objects from which to extract values. Cannot be null.</param>
	/// <returns>An array of type <typeparamref name="T"/> containing the values of all items in the collection. The array will be
	/// empty if the collection contains no items.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	public static T[] Collect<T>(this IReadOnlyCollection<RandItem<T>> collection)
	{
		if (collection == null) throw new ArgumentNullException(nameof(collection));

		return Collect(collection, collection.Count);
	}

	/// <summary>
	/// Generates an array of values by invoking the random value generator of each item in the specified collection, up to
	/// the specified count.
	/// </summary>
	/// <remarks>If the collection contains fewer items than the specified count, only values from the available
	/// items are generated. Each value is produced by calling NextValue() on the corresponding <see cref="RandItem{T}"/> in the
	/// collection.</remarks>
	/// <typeparam name="T">The type of values generated by the random items.</typeparam>
	/// <param name="collection">The collection of random items to generate values from. Cannot be null.</param>
	/// <param name="count">The number of values to generate. Must be zero or greater.</param>
	/// <returns>An array containing up to the specified number of generated values. The array will be empty if count is zero or the
	/// collection contains no items.</returns>
	/// <exception cref="ArgumentNullException">Thrown if collection is null.</exception>
	/// <exception cref="ArgumentOutOfRangeException">Thrown if count is less than zero.</exception>
	public static T[] Collect<T>(this IEnumerable<RandItem<T>> collection, int count)
	{
		if (collection == null) throw new ArgumentNullException(nameof(collection));
		if (count < 0) throw new ArgumentOutOfRangeException(nameof(count), count, null);
		if (count == 0) return [];

		var result = new T[count];
		int i = 0;
		foreach (var item in collection)
		{
			result[i] = item.NextValue();
			if (++i >= count)
				break;
		}
		if (i < count)
			Array.Resize(ref result, i);
		return result;
	}
}